language: python
sudo: false
# command to install dependencies
install: "pip install -U tox setuptools"
# # command to run tests
env:
  matrix:
    - TESTENV=py27
    - TESTENV=py34
    - TESTENV=coveralls
script: "tox --recreate -e $TESTENV"
branches:
    except:
        - /^\d/
notifications:
    email:
        - bubenkoff@gmail.com
