language: python
sudo: false
# command to install dependencies
install: "pip install -U tox"
# # command to run tests
env:
  matrix:
    - TESTENV=py26
    - TESTENV=py27
    - TESTENV=py34
    - TESTENV=coveralls
branches:
    except:
        - /^\d/
notifications:
    email:
        - bubenkoff@gmail.com
